### ISSUE TITLE
Loads of errors in the loader/auth + general questions

### ISSUE THREAD

**Issue by Daxis123** [manolia/P2C-Loader-and-Auth-System#2]
Alright so sorry if this is annoying, feel free to close the issue if you can't be bothered to answer, I just really want to move away from AuthGG so any help would be appreciated. Anyways so I set up the PHP scripts on my VPS and the panel is all working, but then I tried to compile the loader before adding the auth to my program just to test, and I got a ton of errors. A lot of them I fixed by adding _CRT_SECURE_NO_WARNINGS to the preprocessor definitions, but all the other ones seem more complicated to fix. Also how does the auth actually work, like do I put in a password on the panel and then that password someone would use to login or do I login to the panel and then do stuff to users from there? Anyways I'm trash at PHP and anything web related. Any help would really be appreciated but I completely understand if you don't want to deal with this bullshit and just wanna close the issue.

![a](https://user-images.githubusercontent.com/86669063/123812078-b3c6da80-d8eb-11eb-9a4e-d3519f62776c.png)

**Comment by manolia** [comment]
First of all learn cpp i suggest learncpp.com 2nd of all shouldn't be too hard to read the php. Once you have looked at the php you would know what tables etc needs to be made for the database aswell as how the auth would work. Its license based there is no user:pass its just you generating a license and the user using the license as login on the loader.
